after-login-command = []

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-b = 'workspace B'
    alt-f = 'workspace F'
    alt-n = 'workspace N'
    alt-t = 'workspace T'
    alt-v = 'workspace V'
    alt-w = 'workspace W'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-b = 'move-node-to-workspace B'
    alt-shift-f = 'move-node-to-workspace F'
    alt-shift-n = 'move-node-to-workspace N'
    alt-shift-t = 'move-node-to-workspace T'
    alt-shift-v = 'move-node-to-workspace V'
    alt-shift-w = 'move-node-to-workspace W'

    alt-m = 'fullscreen'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
  if.app-id = 'net.kovidgoyal.kitty'
  run = 'move-node-to-workspace T'

[[on-window-detected]]
  if.app-id = 'org.mozilla.firefox'
  run = 'move-node-to-workspace B'

[[on-window-detected]]
  if.app-id = 'app.zen-browser.zen'
  run = 'move-node-to-workspace B'

[[on-window-detected]]
  if.app-id = 'notion.id'
  run = 'move-node-to-workspace N'

[[on-window-detected]]
  if.app-id = 'com.apple.finder'
  run = 'move-node-to-workspace F'

[[on-window-detected]]
  if.app-id = 'ch.protonvpn.mac'
  run = 'layout floating'

[[on-window-detected]]
  if.window-title-regex-substring = 'mpv'
  run = 'move-node-to-workspace V'


[[on-window-detected]]
  if.app-id = 'net.whatsapp.WhatsApp'
  run = 'move-node-to-workspace W'
